version: '3'

services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.6
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: crud_docker_php
      MYSQL_USER: jdvpl
      MYSQL_PASSWORD: jdvpl
      MYSQL_ROOT_PASSWORD: jdvpl
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/www/html  
    restart: always
    
  web:
    image: php:7.3-apache
    container_name: docker-php
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    restart: always  
    links:
      - mysql